export const listCategory = [
  { name: "Hành Động", value: "hanh-dong" },
  { name: "Tình Cảm", value: "tinh-cam" },
  { name: "Hài Hước", value: "hai-huoc" },
  { name: "Cổ Trang", value: "co-trang" },
  { name: "Tâm Lý", value: "tam-ly" },
  { name: "Hình Sự", value: "hinh-su" },
  { name: "Chiến Tranh", value: "chien-tranh" },
  { name: "Thể Thao", value: "the-thao" },
  { name: "Võ Thuật", value: "vo-thuat" },
  { name: "Viễn Tưởng", value: "vien-tuong" },
  { name: "Phiêu Lưu", value: "phieu-luu" },
  { name: "Khoa Học", value: "khoa-hoc" },
  { name: "Kinh Dị", value: "kinh-di" },
  { name: "Âm Nhạc", value: "am-nhac" },
  { name: "Thần Thoại", value: "tai-lieu" },
  { name: "Tài Liệu", value: "than-thoai" },
  { name: "Gia Đình", value: "gia-dinh" },
  { name: "Chính kịch", value: "chinh-kich" },
  { name: "Bí ẩn", value: "bi-an" },
  { name: "Học Đường", value: "hoc-duong" },
  { name: "Kinh Điển", value: "kinh-dien" },
  { name: "Phim 18+", value: "phim-18" },
];

export const listType = [
  { name: "Phim Bộ", value: "phim-bo" },
  { name: "Phim Lẻ", value: "phim-le" },
  { name: "Phim Mới", value: "phim-moi" },
  { name: "TV Shows", value: "tv-shows" },
  { name: "Hoạt Hình", value: "hoat-hinh" },
  { name: "Phim Vietsub", value: "phim-vietsub" },
  { name: "Phim Thuyết Minh", value: "phim-thuyet-minh" },
  { name: "Phim Lồng Tiếng", value: "phim-long-tieng" },
  { name: "Phim Bộ Đang Chiếu", value: "phim-bo-dang-chieu" },
  { name: "Phim Trọn Bộ", value: "phim-bo-hoan-thanh" },
  { name: "Phim Sắp Chiếu", value: "phim-sap-chieu" },
  { name: "Subteam", value: "subteam" },
];

export const listSortField = [
  { name: "Thời gian cập nhật", value: "modified.time" },
  { name: "Thời gian đăng", value: "_id" },
  { name: "Năm sản xuất", value: "year" },
];

export const listCountry = [
  { name: "Hàn Quốc", value: "han-quoc" },
  { name: "Trung Quốc", value: "trung-quoc" },
  { name: "Nhật Bản", value: "nhat-ban" },
  { name: "Thái Lan", value: "thai-lan" },
  { name: "Âu Mỹ", value: "au-my" },
  { name: "Đài Loan", value: "dai-loan" },
  { name: "Hồng Kông", value: "hong-kong" },
  { name: "Ấn Độ", value: "an-do" },
  { name: "Anh", value: "anh" },
  { name: "Pháp", value: "phap" },
  { name: "Canada", value: "canada" },
  { name: "Đức", value: "duc" },
  { name: "Tây Ban Nha", value: "tay-ban-nha" },
  { name: "Thổ Nhĩ Kỳ", value: "tho-nhi-ky" },
  { name: "Hà Lan", value: "ha-lan" },
  { name: "Indonesia", value: "indonesia" },
  { name: "Nga", value: "nga" },
  { name: "Mexico", value: "mexico" },
  { name: "Ba lan", value: "ba-lan" },
  { name: "Úc", value: "uc" },
  { name: "Thụy Điển", value: "thuy-dien" },
  { name: "Malaysia", value: "malaysia" },
  { name: "Brazil", value: "brazil" },
  { name: "Philippines", value: "philippines" },
  { name: "Bồ Đào Nha", value: "bo-dao-nha" },
  { name: "Ý", value: "y" },
  { name: "Đan Mạch", value: "dan-mach" },
  { name: "UAE", value: "uae" },
  { name: "Na Uy", value: "na-uy" },
  { name: "Thụy Sĩ", value: "thuy-si" },
  { name: "Châu Phi", value: "chau-phi" },
  { name: "Nam Phi", value: "nam-phi" },
  { name: "Ukraina", value: "ukraina" },
  { name: "Ả Rập Xê Út", value: "a-rap-xe-ut" },
  { name: "Quốc Gia Khác", value: "quoc-gia-khac" },
];
