export const listCategory = [
  { name: "Hành Động", value: "hanh-dong" },
  { name: "Tình Cảm", value: "tinh-cam" },
  { name: "Hài Hước", value: "hai-huoc" },
  { name: "Cổ Trang", value: "co-trang" },
  { name: "Tâm Lý", value: "tam-ly" },
  { name: "Hình Sự", value: "hinh-su" },
  { name: "Chiến Tranh", value: "chien-tranh" },
  { name: "Thể Thao", value: "the-thao" },
  { name: "Võ Thuật", value: "vo-thuat" },
  { name: "Viễn Tưởng", value: "vien-tuong" },
  { name: "Phiêu Lưu", value: "phieu-luu" },
  { name: "Khoa Học", value: "khoa-hoc" },
  { name: "Kinh Dị", value: "kinh-di" },
  { name: "Âm Nhạc", value: "am-nhac" },
  { name: "Thần Thoại", value: "tai-lieu" },
  { name: "Tài Liệu", value: "than-thoai" },
  { name: "Gia Đình", value: "gia-dinh" },
  { name: "Chính kịch", value: "chinh-kich" },
  { name: "Bí ẩn", value: "bi-an" },
  { name: "Học Đường", value: "hoc-duong" },
  { name: "Kinh Điển", value: "kinh-dien" },
  { name: "Phim 18+", value: "phim-18" },
];

export const listType = [
  { name: "Phim Bộ", value: "phim-bo" },
  { name: "Phim Lẻ", value: "phim-le" },
  { name: "Phim Mới", value: "phim-moi" },
  { name: "TV Shows", value: "tv-shows" },
  { name: "Hoạt Hình", value: "hoat-hinh" },
  { name: "Phim Vietsub", value: "phim-vietsub" },
  { name: "Phim Thuyết Minh", value: "phim-thuyet-minh" },
  { name: "Phim Lồng Tiếng", value: "phim-long-tieng" },
  { name: "Phim Bộ Đang Chiếu", value: "phim-bo-dang-chieu" },
  { name: "Phim Trọn Bộ", value: "phim-bo-hoan-thanh" },
  { name: "Phim Sắp Chiếu", value: "phim-sap-chieu" },
  { name: "Subteam", value: "subteam" },
];

export const listSortField = [
  { name: "Thời gian cập nhật", value: "modified.time" },
  { name: "Thời gian đăng", value: "_id" },
  { name: "Năm sản xuất", value: "year" },
];

export const listCountry = [
  { name: "Hàn Quốc", value: "han-quoc" },
  { name: "Trung Quốc", value: "trung-quoc" },
  { name: "Nhật Bản", value: "nhat-ban" },
  { name: "Thái Lan", value: "thai-lan" },
  { name: "Âu Mỹ", value: "au-my" },
  { name: "Đài Loan", value: "dai-loan" },
  { name: "Hồng Kông", value: "hong-kong" },
  { name: "Ấn Độ", value: "an-do" },
  { name: "Anh", value: "anh" },
  { name: "Pháp", value: "phap" },
  { name: "Canada", value: "canada" },
  { name: "Đức", value: "duc" },
  { name: "Tây Ban Nha", value: "tay-ban-nha" },
  { name: "Thổ Nhĩ Kỳ", value: "tho-nhi-ky" },
  { name: "Hà Lan", value: "ha-lan" },
  { name: "Indonesia", value: "indonesia" },
  { name: "Nga", value: "nga" },
  { name: "Mexico", value: "mexico" },
  { name: "Ba lan", value: "ba-lan" },
  { name: "Úc", value: "uc" },
  { name: "Thụy Điển", value: "thuy-dien" },
  { name: "Malaysia", value: "malaysia" },
  { name: "Brazil", value: "brazil" },
  { name: "Philippines", value: "philippines" },
  { name: "Bồ Đào Nha", value: "bo-dao-nha" },
  { name: "Ý", value: "y" },
  { name: "Đan Mạch", value: "dan-mach" },
  { name: "UAE", value: "uae" },
  { name: "Na Uy", value: "na-uy" },
  { name: "Thụy Sĩ", value: "thuy-si" },
  { name: "Châu Phi", value: "chau-phi" },
  { name: "Nam Phi", value: "nam-phi" },
  { name: "Ukraina", value: "ukraina" },
  { name: "Ả Rập Xê Út", value: "a-rap-xe-ut" },
  { name: "Quốc Gia Khác", value: "quoc-gia-khac" },
];

export const listAvatar = [
  "https://ih0.redbubble.net/image.618379802.1473/flat,1000x1000,075,f.u2.jpg",
  "https://upload.wikimedia.org/wikipedia/commons/0/0b/Netflix-avatar.png",
  "https://mir-s3-cdn-cf.behance.net/project_modules/disp/84c20033850498.56ba69ac290ea.png",
  "https://i.pinimg.com/originals/34/62/d2/3462d27440aa255b1c314ff16f4032b4.png",
  "https://ih0.redbubble.net/image.618369215.1083/flat,1000x1000,075,f.u2.jpg",
  "https://img.freepik.com/premium-vector/world-smile-day-template-free-vector_668862-43.jpg?w=2000",
  "https://wallpapers.com/images/hd/netflix-profile-pictures-1000-x-1000-88wkdmjrorckekha.jpg",
  "https://i.pinimg.com/474x/c0/8e/6c/c08e6c9595e03202a46a95f66578799f--netflix-girly-things.jpg",
  "https://i.pinimg.com/474x/fb/8e/8a/fb8e8a96fca2f049334f312086a6e2f6--vini-cata.jpg",
  "https://mir-s3-cdn-cf.behance.net/project_modules/disp/e70b1333850498.56ba69ac32ae3.png",
  "https://secure.gravatar.com/avatar/334c7ba02038cbb927ecfc119a8a866d?s=384",
  "https://avatars.githubusercontent.com/u/4508878?v=4",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwLdXdV6iK8jJ68gYlNACzegdITim31yFUKA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiSRIlNla0MmNXBSJofMMenqC5UxAQQaiSMg&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMqzpWUwgJWNWIRp7bC8rDZgtju1JQERuP-A&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZGiackbaemHrAPHL7AXhfr-j0fhn3RZVXAQ&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcwUqplWbmtLvmGJEd3EPlCNY1j4PyIjP5Kg&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3EplfCkREEWGLe9IaI8sEfXSA36awr9Apzw&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwAEjpByBZ_Q63VU3EVbl5i1VqydqWgYr4KA&s",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD6gvzn1GdKNUXEHFYz9x0ZoCq8TCWAXsZwA&s",
];
